CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    class VARCHAR(50) NOT NULL,
    major VARCHAR(100) NOT NULL,
    faculty VARCHAR(100) NOT NULL,
    school VARCHAR(100) NOT NULL,
    phone VARCHAR(15) UNIQUE,
    email VARCHAR(100) UNIQUE,
    address VARCHAR(255)
);
